/**
 * GENERATOR (#457 slice 2, truth pipeline): renders docs/reference/events.md
 * from the runtime's SSE wire manifest (`sse-event-manifest.json`) — the same
 * artifact the dashboard's drift test guards. Docs join that discipline:
 * generated, committed, drift-checked.
 *
 *   bun run tools/gen-docs-event-reference.ts          # regenerate
 *   bun run tools/gen-docs-event-reference.ts --check  # CI drift gate (exit 1 on stale)
 *
 * The page is a catalog (names, grouped by family) with pointers to the typed
 * source of truth — payload-level docs stay in events/types.ts where the
 * compiler guards them; this page can never silently omit a wire event.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(repo, "packages/agent-runtime/src/transport/sse-event-manifest.json");
const outPath = join(repo, "docs/reference/events.md");

const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
  $comment: string;
  names: string[];
};

const families = new Map<string, string[]>();
for (const name of [...manifest.names].sort()) {
  const family = name.includes(".") ? (name.split(".")[0] as string) : "(lifecycle)";
  const list = families.get(family) ?? [];
  list.push(name);
  families.set(family, list);
}

const lines: string[] = [
  "---",
  'title: "SSE Event Reference"',
  'description: "Every event name on the SSE wire — generated from the runtime manifest, drift-checked in CI."',
  "---",
  "",
  "<!-- GENERATED by tools/gen-docs-event-reference.ts from",
  "     packages/agent-runtime/src/transport/sse-event-manifest.json.",
  "     Do not edit by hand — regenerate with:",
  "       bun run tools/gen-docs-event-reference.ts -->",
  "",
  `The runtime speaks **${manifest.names.length} wire events** over SSE. This catalog is`,
  "generated from the same manifest the dashboard's drift test enforces, so it",
  "cannot silently fall behind the wire vocabulary: adding or renaming an event",
  "without regenerating this page fails CI.",
  "",
  "Payload shapes live with the compiler where they are guarded by types:",
  "`packages/agent-runtime/src/events/types.ts` (event objects) and",
  "`packages/agent-runtime/src/transport/sse-formatter.ts` (wire mapping).",
  "",
];

for (const [family, names] of [...families.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  lines.push(`## \`${family}\``, "");
  for (const name of names) {
    lines.push(`- \`${name}\``);
  }
  lines.push("");
}

const next = `${lines.join("\n").trimEnd()}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outPath, "utf8");
  } catch {
    // missing file counts as stale
  }
  if (current !== next) {
    console.error(
      "docs/reference/events.md is stale relative to sse-event-manifest.json — run: bun run tools/gen-docs-event-reference.ts",
    );
    process.exit(1);
  }
  console.log("docs/reference/events.md is current");
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, next);
  console.log(`wrote ${outPath} (${manifest.names.length} events)`);
}
