#!/usr/bin/env bun
/**
 * Generate the committed SSE wire-vocabulary manifest from the runtime's
 * authoritative `SSE_WIRE_EVENT_NAMES` (#286/#324).
 *
 * WHY A MANIFEST (and not a direct import from the dashboard):
 * The dashboard is architecturally STANDALONE — it declares no dependency on
 * `@agentic-patterns/runtime` (see CLAUDE.md), and #291 exists to keep its
 * browser bundle (`graph/`, `chat/`) from importing runtime/server code (the
 * `bun:sqlite` hazard). So the dashboard union cannot import the runtime union
 * directly. Instead this generator — which runs under Bun at the repo root,
 * never in the browser bundle — emits a small committed JSON the dashboard's
 * drift-check test reads via `fs`. A runtime-side test asserts the manifest is
 * in sync with `SSE_WIRE_EVENT_NAMES`; the dashboard test asserts its client
 * union covers every name in the manifest. CI fails on either divergence.
 *
 * Run: `bun run tools/gen-sse-manifest.ts` (requires `packages/*` built — it
 * imports the public runtime surface, matching the `check-model-facing-schemas`
 * precedent). The runtime test `sse-wire-manifest.test.ts` tells you to re-run
 * this whenever the wire vocabulary changes.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SSE_WIRE_EVENT_NAMES } from "@agentic-patterns/runtime";

const MANIFEST_PATH = join(
  import.meta.dir,
  "..",
  "packages",
  "agent-runtime",
  "src",
  "transport",
  "sse-event-manifest.json",
);

const manifest = {
  $comment:
    "GENERATED by tools/gen-sse-manifest.ts from the runtime's SSE_WIRE_EVENT_NAMES. " +
    "Do not edit by hand. The dashboard's sse-events drift-check reads this file. " +
    "Re-run `bun run tools/gen-sse-manifest.ts` when the wire vocabulary changes.",
  names: [...SSE_WIRE_EVENT_NAMES].sort(),
};

writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Wrote ${manifest.names.length} SSE wire names to ${MANIFEST_PATH}`);
